version: '3'
services:

    api.laravel:
        build: api/laravel/core
        volumes:
            - './api/laravel/core:/var/www/html'
        command: 'php artisan serve --host=0.0.0.0'
        ports:
            - '8000:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        environment:
            - NAME=api.laravel
        env_file:
            - .env

    redis.socket:
        image: 'redis:alpine'
        volumes:
            - './volumes/db/redis/sockets:/data'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121

    socket.jonny:
        build: ./sockets/socket_instance
        ports:
            - "3000:3000"
        volumes:
            - ./sockets/socket_instance:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        depends_on:
            - redis.socket
        environment:
            - SERVER_NAME=socket.jonny
        env_file:
            - .env

    storage.minio:
        build: ./storages/minio
        ports:
            - "9000:9000"
            - "9009:9009"
        volumes:
            - ./volumes/storages/minio:/data
        env_file:
            - .env
        command: server --console-address :9009 /data
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121

    front.admin:
        build: ./front/admin
        volumes:
            - ./front/admin:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        environment:
            - NAME=front.admin
        env_file:
            - .env

    front.public:
        build: ./front/public
        volumes:
            - ./front/public:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        environment:
            - NAME=front.public
        env_file:
            - .env

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        ports:
            - "80:80"
        depends_on:
            - front.public
            - front.admin

networks:
    pv121:
        driver: bridge
