version: '3'
services:

    redis.socket:
        image: 'redis:alpine'
        volumes:
            - './volumes/db/redis/sockets:/data'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121

    socket.jonny:
        build: ./sockets/socket_instance
        ports:
            - "3000:3000"
        volumes:
            - ./sockets/socket_instance:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121
        depends_on:
            - redis.socket
        environment:
            - SERVER_NAME=socket.jonny
        env_file:
            - .env

    storage.minio:
        build: ./storages/minio
        ports:
            - "9000:9000"
            - "9009:9009"
        volumes:
            - ./volumes/storages/minio:/data
        env_file:
            - .env
        command: server --console-address :9009 /data
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - pv121

networks:
    pv121:
        driver: bridge
